- bpmn-files/README.md
Some files have been renamed and added, so update to have a quick overview of the test diagrams
> BPMN diagrams: update readme with screenshots

- README.md
- examples/custom-fonts/README.md
- examples/custom-fonts/index.html
- examples/index.html
**WIP depends on #15** (global index.html page) 
Custom font examples for the 0.1.5 version
Display the following on the same page
- default font
- custom default font
- custom font for pool and user task
> feat(example): custom fonts

- scripts/update-lib-version.bash
Tested by running it from the 'root', 'scripts' and 'examples/demo' folders.
> chore(update): provide a script to update examples on new lib release

- README.md
In addition
- add license badge
- move badges close to the page title
> [DOC] highlight demo and examples live environments

- examples/load-remote-bpmn-diagrams/index.html
> [FIX] load remote diagram example - scrollable viewport

- examples/load-remote-bpmn-diagrams/index.html
> [FEAT] updated design for  button and status in remote fetching example

- examples/hacktoberfest-diagram/hacktoberfest-diagram.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/fix_hacktoberfest_diagram/examples/index.html
> [FIX] Fix typo on Hacktoberfest example

- demo/index.html
- examples/01-getting-started/README.md
- examples/01-getting-started/index.html
- examples/custom-colors/custom-colors.js
- examples/custom-colors/index.html
- examples/custom-fonts/custom-fonts.js
- examples/custom-fonts/index.html
- examples/custom-user-task-icon/custom-user-task-icon.js
- examples/custom-user-task-icon/index.html
- examples/diagram-navigation/index.html
- examples/hacktoberfest-diagram/hacktoberfest-diagram.js
- examples/hacktoberfest-diagram/index.html
- examples/load-local-bpmn-diagrams/index.html
- examples/load-remote-bpmn-diagrams/index.html
- examples/utils.js
[__:fast_forward: Live demo while this PR is opened__](https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/build-0.5.0/examples/index.html)
> [INFRA] bump version - 0.5.0

- examples/projects/typescript-vanilla-with-rollup/package.json
- scripts/update-lib-version.bash
> [INFRA] bump version - 0.5.0 for vanilla ts project

- examples/load-remote-bpmn-diagrams/index.html
Add the newly available diagram from miwg-test-suite
> [FEAT] load remote bpmn - add C.7.0

- examples/diagram-fit-variants/index.html
:arrow_forward:  [Live environment](https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/fit_example_update_margin_wording/examples/diagram-fit-variants/index.html)
> [FEAT] 'fit variants' example: update margin wording

- examples/custom-colors/index.html
- examples/custom-fonts/index.html
- examples/hacktoberfest-diagram/index.html
- examples/index.html
- examples/static/css/main.css
> [FEAT] Always display navbar

- examples/01-getting-started/README.md
- examples/01-getting-started/index.html
- examples/custom-colors/README.md
- examples/custom-colors/custom-colors.js
- examples/custom-colors/index.html
- examples/custom-fonts/README.md
- examples/custom-fonts/custom-fonts.js
- examples/custom-fonts/index.html
- examples/custom-user-task-icon/README.md
- examples/custom-user-task-icon/custom-user-task-icon.js
- examples/custom-user-task-icon/index.html
- examples/diagram-fit-on-load/README.md
- examples/diagram-fit-on-load/diagram-fit-on-load.js
- examples/diagram-fit-on-load/index.html
- examples/diagram-fit-variants/index.html
- examples/diagram-navigation/README.md
- examples/diagram-navigation/index.html
- examples/hacktoberfest-diagram/README.md
- examples/hacktoberfest-diagram/hacktoberfest-diagram.js
- examples/hacktoberfest-diagram/index.html
- examples/load-local-bpmn-diagrams/index.html
- examples/load-remote-bpmn-diagrams/README.md
- examples/load-remote-bpmn-diagrams/index.html
- examples/projects/typescript-vanilla-with-rollup/src/app/initialize.ts
- examples/projects/typescript-vanilla-with-rollup/src/index.html
Covers https://github.com/process-analytics/bpmn-visualization-js/issues/866
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/refactor/update_bpmn_container_div_id/examples/index.html
> [REFACTOR] use `bpmn-container` div id in examples

- README.md
- examples/custom-colors/README.md
- examples/custom-colors/custom-colors.js
- examples/custom-colors/index.html
- examples/custom-fonts/README.md
- examples/custom-fonts/custom-fonts.js
- examples/custom-fonts/index.html
- examples/custom-user-task-icon/README.md
- examples/custom-user-task-icon/custom-user-task-icon.js
- examples/custom-user-task-icon/index.html
- examples/hacktoberfest-diagram/README.md
- examples/hacktoberfest-diagram/hacktoberfest-diagram.js
- examples/hacktoberfest-diagram/index.html
- examples/load-remote-bpmn-diagrams/README.md
- examples/load-remote-bpmn-diagrams/index.html
- examples/utils.js
- scripts/update-lib-version.bash
closes #85
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/85-do_not_use_demo_package_in_examples/examples/index.html
> [FEAT] Do not use demo package in examples

- README.md
- examples/custom-colors/README.md
- examples/custom-fonts/README.md
- examples/custom-user-task-icon/README.md
- examples/hacktoberfest-diagram/README.md
Update the documentation here after changes on the lib documentation (see https://github.com/process-analytics/bpmn-visualization-js/pull/904).
> [DOC] update links to bpmn-visualization documentation

- examples/index.html
info: no smooth scroll due to lack of support https://caniuse.com/?search=scroll-behavior (as when clicking on summary links)
closes #102
relates to #104 
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/102-back_to_top_not_working_on_safari/examples/index.html
> [BUG] back to top fix for safari

- examples/custom-animation/growing-sequence-flow/README.md
- examples/custom-animation/growing-sequence-flow/index.html
- examples/custom-animation/growing-sequence-flow/index.js
- examples/custom-animation/running-dashed-message-flow/README.md
- examples/custom-animation/running-dashed-message-flow/index.html
- examples/custom-animation/running-dashed-message-flow/index.js
**Title**
Update demos under the custom animation section to use the new API available in 0.11.0
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/chore-update_demos_custom_animation/examples/index.html
> Update 'custom animation' examples for bpmn-visualization@0.11.0

- examples/custom-interaction/javascript-tooltip-and-popover/index.html
For both css and js resources loaded from CDN and not managed by our project.
closes #121
> [FEAT] Check 'Subresource Integrity' for external resources

- examples/custom-animation/growing-sequence-flow/index.html
- examples/custom-animation/running-dashed-message-flow/index.html
- examples/custom-bpmn-theme/custom-colors/index.html
- examples/custom-bpmn-theme/custom-fonts/index.html
- examples/custom-bpmn-theme/custom-user-task-icon/index.html
- examples/custom-bpmn-theme/hacktoberfest-diagram/index.html
- examples/custom-interaction/apply-css-classes/index.html
- examples/custom-interaction/javascript-tooltip-and-popover/index.html
- examples/custom-interaction/popover-static/index.html
- examples/custom-interaction/select-elements-by-bpmn-kind/index.html
- examples/custom-navigation/call-activity-with-modal-on-mouse-over/index.html
- examples/custom-navigation/call-activity-with-reload-on-dblclick/index.html
- examples/custom-navigation/call-activity-with-tabs-on-click/index.html
- examples/diagram-navigation/diagram-fit-after-load/index.html
- examples/diagram-navigation/diagram-fit-on-load/index.html
- examples/diagram-navigation/diagram-navigation/index.html
- examples/display-bpmn-diagram/01-getting-started/README.md
- examples/display-bpmn-diagram/01-getting-started/index.html
- examples/display-bpmn-diagram/load-local-bpmn-diagrams/index.html
- examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.html
- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-kie-editors-standalone/index.html
Closes #125
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/125-Use_minified_version/examples/index.html
> [EXAMPLE] Update examples to use minified IIFE bundle

- examples/custom-navigation/call-activity-with-modal-on-mouse-over/README.md
- examples/custom-navigation/call-activity-with-modal-on-mouse-over/index.html
- examples/custom-navigation/call-activity-with-modal-on-mouse-over/index.js
- examples/custom-navigation/call-activity-with-reload-on-dblclick/README.md
- examples/custom-navigation/call-activity-with-reload-on-dblclick/index.js
- examples/custom-navigation/call-activity-with-tabs-on-click/README.md
- examples/custom-navigation/call-activity-with-tabs-on-click/index.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/use_new_add_css_class_api_when_possible/examples/index.html
> Call activity navigation examples: use new 'add css classes' API when possible and enable navigation

- examples/custom-interaction/apply-css-classes/README.md
- examples/custom-interaction/apply-css-classes/index.html
Provided by bpmn-visualization@0.12.0-0
closes #138 
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/138-use_new_remove_and_toggle_css_api/examples/index.html
> Examples: use new remove and toggle CSS classes API

- .github/pull_request_template.md
To avoid to remove the demo link when a pull request is created, up it
> [INFRA] Update Pull Request template

- scripts/update-lib-version.bash
Tested on Ubuntu 18.04 with the following examples versions back and forth
```
0.12.1
0.12.1-1
0.12.1-alpha-1
```
> [INFRA] Update the script to manage pre-release

- .github/workflows/update_bpmn_visualization_version.yml
Fix reviewers list
Tested on https://github.com/process-analytics/github-actions-playground/actions/runs/632009606
> [FIX] Fix the workflow to update the BPMN Visualization version

- examples/custom-interaction/javascript-tooltip-and-popover/index.js
- examples/custom-interaction/popover-static/README.md
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/1261-Replace_'panning'_by_'pan'/examples/index.html
Covers https://github.com/process-analytics/bpmn-visualization-js/issues/1261
> [DOC] Replace 'panning' by 'pan'

- examples/diagram-navigation/diagram-navigation/index.html
covers https://github.com/process-analytics/bpmn-visualization-js/issues/847
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/update_navigation_example_description/examples/index.html
> [FEAT] update usage in the diagram navigation page

- scripts/update-lib-version.bash
The script was only able to update the examples, it has been refactored to also
manage assets in the demo folder.
covers https://github.com/process-analytics/bpmn-visualization-js/issues/1174
> [INFRA] Fix script to update the lib version in the demos

- demo/monitoring-all-process-instances/execution-data.js
- demo/monitoring-all-process-instances/index.html
- demo/monitoring-all-process-instances/index.js
- examples/static/js/bpmn-diagrams.js
- specific page: https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/customize_paths_on_demo_monitoring/demo/monitoring-all-process-instances/index.html
- home: https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/customize_paths_on_demo_monitoring/examples/index.html
covers #187
> [FEAT] Customize paths on the demo monitoring

- .github/workflows/update_bpmn_visualization_version.yml
Tested with https://github.com/process-analytics/github-actions-playground/pull/27 & https://github.com/process-analytics/github-actions-playground/actions/runs/950509102
> [INFRA] Remove Marcin from the auto reviewers

- demo/monitoring-all-process-instances/index.html
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/change_design_of_monitoring_page/examples/index.html
> [FEAT] Monitoring demo : Update the design of the panel for the legends & diagram

- demo/monitoring-all-process-instances/index.html
- demo/monitoring-all-process-instances/js/index.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/monitoring_demo/improve_button_css/examples/index.html
> [FEAT] Demo time/frequency monitoring: Improve button style

- examples/projects/javascript-vanilla-with-webpack/package-lock.json
- examples/projects/javascript-vanilla-with-webpack/package.json
- examples/projects/typescript-vanilla-with-rollup/.eslintrc.js
- examples/projects/typescript-vanilla-with-rollup/README.md
- examples/projects/typescript-vanilla-with-rollup/package-lock.json
- examples/projects/typescript-vanilla-with-rollup/package.json
- examples/projects/typescript-vanilla-with-rollup/rollup.config.js
JavaScript project: bump dev dependencies
TypeScript project:
- bump dev dependencies
- readme: simplify start command
- eslint: fix configuration files
> [FEAT] Update JavaScript and TypeScript projects

- demo/monitoring-all-process-instances/index.html
- demo/monitoring-all-process-instances/js/frequency-execution-data.js
- demo/monitoring-all-process-instances/js/index.js
- demo/monitoring-all-process-instances/js/legend.js
- demo/monitoring-all-process-instances/js/time-execution-data.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/monitoring_demo/introduce_legend_class/examples/index.html
latest commit: https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/98883710ef1dfc3181d47517b676af774ac7eb8e/examples/index.html
The code is not perfect, but it will be improved in the next PRs.
> [REFACTOR] Demo time/frequency monitoring: Introduce Legend class

- demo/monitoring-all-process-instances/index.html
- demo/monitoring-all-process-instances/js/index.js
- demo/monitoring-all-process-instances/js/use-case.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/monitoring_demo/introduce_use_case_class/examples/index.html
The code is not perfect, but it will be improved in the next PRs.
> [REFACTOR] Demo time/frequency monitoring: Introduce UseCase classes

- demo/monitoring-all-process-instances/js/index.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/monitoring_demo/introduce_state_for_buttons/examples/index.html
> [REFACTOR] Demo time/frequency monitoring: Introduce state for buttons

- demo/monitoring-all-process-instances/css/legend.css
- demo/monitoring-all-process-instances/index.html
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/monitoring_demo/legend_titles/examples/index.html
> [FEAT] Demo time/frequency monitoring: Add legend titles

- demo/monitoring-all-process-instances/index.html
- demo/monitoring-all-process-instances/js/execution-data/execution-data.js
- demo/monitoring-all-process-instances/js/legend.js
- demo/monitoring-all-process-instances/js/use-case.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/monitoring_demo/hide_legend_when_no_necessary/examples/index.html
Covers #204
> [FEAT] Monitoring demo: Hide the legends when it's not necessary

- examples/index.html
Replicate what we have in the repository README. This should clarify the difference between what we call a demo and an example.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/explain_diff_between_demo_and_examples_in_home/examples/index.html (use latest commit)
> [FEAT] Home page explains what a demo is

- examples/misc/compare-with-kie-editors-standalone/index.html
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/bump_kie-editors-standalone/examples/index.html
> [FEAT] Bump kie-editors-standalone from 0.15.0 to 0.16.0

- .github/workflows/update_bpmn_visualization_version.yml
> [INFRA] Update release PR reviewers

- examples/projects/typescript-vanilla-with-vitejs/README.md
- examples/projects/typescript-vanilla-with-vitejs/package.json
> [INFRA] Simplify the vite TypeScript project startup

- .github/dependabot.yml
**Notes**
Configuration for npm will be done later, I would like to remove some dependencies from projects. There are too many for now.
> [INFRA] Configure dependabot for GitHub Actions update

- examples/overlays/custom-overlay-default-style/README.md
This fixes the issue https://github.com/process-analytics/bpmn-visualization-examples/issues/332
closes #332
> [FIX] Fix link to the live environment of the overlays custom default style example

- .github/release.yml
> [INFRA] Configure auto-generated release-notes

- projects/typescript-vanilla-with-parcel/package.json
> [INFRA] Bump devDependencies in the parcel project

- .github/workflows/update_bpmn_visualization_version.yml
Use the exact name of the library in the commit and PR title.
This is now consistent with what we have in other repositories.
> [INFRA] Rework the workflow updating bpmn-visualization

- .github/workflows/check-javascript-projects.yml
- projects/javascript-vanilla-with-webpack/package.json
Ensure the JS projects can be built.
> [INFRA] Check JavaScript projects with a GitHub workflow

- CONTRIBUTING.md
Some elements were not accurate anymore. Instead link to the `bpmn-visualization` release process.
> [DOC] Better explain the release process

- projects/javascript-vanilla-with-webpack/README.md
- projects/typescript-vanilla-with-parcel/README.md
- projects/typescript-vanilla-with-rollup/README.md
- projects/typescript-vanilla-with-vitejs/README.md
> [DOC] Improve the README title in existing projects

- projects/typescript-vanilla-with-parcel/package.json
> [INFRA] Update parcel from 2.7.0 to 2.8.0

- examples/custom-behavior/javascript-tooltip-and-popover/index.js
Previously, only part of the data was displayed in the popover. All these properties are now displayed in a generic way.
They are divided into 2 groups of properties:
- some are displayed first (arbitrary choice and order for main information)
- others are then displayed
- all keys/values can be displayed as they appear in the BPMN semantic, or they can be transformed (based on a dedicated configuration)
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/js-popover_more_bpmn_info/examples/index.html
There is no visual changes for now.
The change will appears when new BPMN semantic data will be return by the bpmn-visualization API, for instance, once https://github.com/process-analytics/bpmn-visualization-js/issues/2504 is implemented.
> feat(js-popover): the popover displays all BPMN semantic data

- projects/typescript-vanilla-with-parcel/package.json
- projects/typescript-vanilla-with-vitejs/package.json
bump parcel from 2.8.2 to 2.8.3
bump vite from 4.0.4 to 4.1.4
> chore(deps): bump dependencies in the parcel and vite projects

- projects/typescript-angular/.npmrc
- projects/typescript-angular/README.md
- projects/typescript-angular/package.json
> chore(deps): bump to angular@15 in the Angular project

- demo/predictions/index.html
- examples/static/js/diagram/bpmn-diagram-bpmn-spec-pizza.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/move_diagram_file/demo/predictions/index.html
> refactor: move bpmn pizza diagram with other bpmn diagrams

- demo/predictions/index.html
- demo/predictions/js/data.js
- demo/predictions/js/prediction-use-case.js
[https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/extract_prediction_data/demo/predictions/index.html](https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/extract_prediction_data/demo/predictions/index.html)  
last commit : https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/b85fbb113c60b3ae7c8192e2c863cf4d76f4a9e7/demo/predictions/index.html
> refactor: extract the data for the prediction demo in dedicated classes

- demo/predictions/css/demo.css
- demo/predictions/css/legend.css
- demo/predictions/index.html
- demo/predictions/js/prediction-use-case.js
- demo/predictions/js/style.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/260-desactivate_mavigation/demo/predictions/index.html
Depends #525 
Covers #260
> feat(prediction): deactivate the navigation

- demo/prediction/css/demo.css
- demo/prediction/index.html
- demo/prediction/js/data.js
- demo/prediction/js/prediction-use-case.js
- demo/prediction/js/style.js
- demo/static/js/use-case.js
[https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/260-add_popup_popover/examples/index.html](https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/260-add_popup_popover/examples/index.html)
https://github.com/process-analytics/bpmn-visualization-examples/assets/4921914/1cd6bae1-2fb6-4181-9751-566082c64c08
Closes #530
> feat(prediction): add popup popover

- demo/hacktoberfest-custom-themes/index.html
- demo/hacktoberfest-custom-themes/js/theme.js
[https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/552-Hacktoberfest_2023/examples/index.html](https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/552-Hacktoberfest_2023/examples/index.html)
Closes #552
> feat(hacktoberfest): add 2023 theme

- demo/hacktoberfest-custom-themes/index.html
Use shorter text and reduce the margins to leave more space for the demonstration itself.
covers #456
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/hacktoberfest_demo_description/examples/index.html
> feat: simplify the description in the Hacktoberfest demo

- demo/prediction/index.html
- demo/prediction/js/index.js
- demo/prediction/js/prediction-use-case.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/deee93c/demo/prediction/index.html
Closes #526
> refactor(demo): have a single bpmn container in the prediction demo

- demo/monitoring-all-process-instances/index.html
- demo/monitoring-all-process-instances/js/index.js
- demo/monitoring-all-process-instances/js/monitoring-use-case.js
I will do another PR to refactor the UseCase class, and simplify the code.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/500-single_BPMN_container_monitoring_demo/examples/index.html
Closes #500
> refactor(demo): use a single bpmn container in the monitoring demo

- projects/javascript-vanilla-with-webpack/package.json
✔️ Tested with the surge preview environment
> chore: bump webpack dependencies
