process-analytics/bpmn-visualization-examples

- README.md
- examples/custom-user-task-icon/README.md
- examples/custom-user-task-icon/index.html
custom user task icon for the 0.1.5 version
display default and custom icon implementation
> feat(example): custom user task icon

- README.md
- examples/index.html
- examples/load-remote-bpmn-diagrams/README.md
- examples/load-remote-bpmn-diagrams/index.html
**WIP depends on #15 (global index.html page)**
Example for the 0.1.5 version
Randomly fetch a set of BPMN diagrams from miwg-test-suite to demonstrate
integration with bpmn-visualization by clicking on a button.
The fetching status (pending, success with fetch time, error) is displayed as
well.
> feat(example): load remote bpmn diagrams

- examples/custom-colors/custom-colors.js
- examples/custom-fonts/custom-fonts.js
- examples/custom-user-task-icon/custom-user-task-icon.js
Simplify the code readability
covers #18
> examples: bpmn diagrams in dedicated function

- examples/custom-colors/custom-colors.js
- examples/custom-colors/index.html
closes #28 
depends on #29 
The BPMN content has been udpated to show a boundary event.
New example rendering
> example: add custom colors depending on event type

- examples/load-remote-bpmn-diagrams/index.html
Also add missing miwg files: 'A.3.0', 'A.4.0', 'A.4.1'
Final design achieved thanks to the @aibcmars help.
Available live while this PR is opened: https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/load_remote_diagrams_add_dropdown_list/examples/load-remote-bpmn-diagrams/index.html#
> [FEAT] add dropdown to select a specific remote diagram

- examples/diagram-navigation/README.md
- examples/diagram-navigation/index.html
Reset the zoom and diagram position to initial values (i.e. when the diagram is loaded)
Use mxGraph native functions to demonstrate what https://github.com/process-analytics/bpmn-visualization-js/issues/738 will bring to `bpmn-visualization`
> [FEAT] navigation example: allow diagram zoom and pan reset

- examples/misc/compare-with-kie-editors-standalone/README.md
- examples/misc/compare-with-kie-editors-standalone/index.html
Still work when accessing the page served by an http server.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/misc_kie-editors-standalone-compare_allow_to_run_without_http_server/examples/index.html
> [FEAT] kie-editors-standalone example access without http server

- examples/projects/typescript-vanilla-with-rollup/tsconfig.json
Remove extra types declaration in tsconfig.json as we don't have a mxgraph types dependency
in this project.
We have decide to not put mxgraph types in this examples for now.
This may be required for people that want to extend the part our lib relying on mxgraph: the rendering part. We already have js examples for the browser that demonstrate it.
Remember that extensions points are not officially part of the lib and we may replace mxgraph by another lib in a near future (). So, we will then provide examples on this area later.
> Clean Vanilla TypeScript project configuration

- .github/workflows/update_bpmn_visualization_version.yml
Add a new workflow to:
- Catch `repository_dispatch` & `workflow_dispatch` events
- Download the new Demo & replace the old
- Update the BPMN Visualization version in the examples
- Create automatically a Pull Request, by Process Analytics Bot, in draft
-------
To download an artifact or create a Pull request, the Github action need [Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with `repo` rights. But, it need too to have the owner of the token as admin of the repository from running the Github action.
**Result**
- Run the workflow manually: https://github.com/process-analytics/github-actions-playground/actions/runs/624184433
- Run the workflow from a `repository_dispath`event: …
> [INFRA] Add a new worklow to update automatically the lib version

- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-kie-editors-standalone/index.html
Bump
- bpmn-js from 8.0.0 to 8.2.1
- kie-editors-standalone from 0.8.1 to 0.8.3
closes #132
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/bump_bpmn_competitors_lib_versions/examples/index.html
> [FEAT] bump bpmn-js and kie-editors-standalone libs

- examples/index.html
- examples/misc/compare-with-kie-editors-standalone/README.md
The bundle size has decreased when upgrading from 0.8.1 to 0.8.3.
The example doesn't need a web server.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/doc/update_info_about_kie-editors-standalone/examples/index.html
> [DOC] update info about kie-editors-standalone

- examples/index.html
- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-kie-editors-standalone/README.md
- examples/misc/compare-with-kie-editors-standalone/index.html
kie-editors-standalone: bump from 0.8.3 to 0.9.0
Activate the read-only mode that is now available
bpmn-js: bump from 8.2.1 to 8.3.1
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/bump_competitor_libs_version/examples/index.html
> [FEAT] Bump competitor libs used in the comparison examples

- examples/custom-bpmn-theme/custom-colors/custom-colors.js
The Cyan renders pretty badly with a white background (unreadable) -> A deep pink is way better, as always :)
> Update a color used in theme example

- examples/index.html
Replace 'display' by 'rendering'
Remove extra 'example' word from the summary (no need to repeat example here as we are in the example home page)
covers https://github.com/process-analytics/bpmn-visualization-js/issues/1259
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/index_wording_update/examples/index.html
> [FEAT] Align wording of the example home page

- examples/diagram-navigation/diagram-navigation/index.html
- examples/diagram-navigation/diagram-navigation/index.js
Only keep a single container where the user can do 'diagram navigation': this
let us have a larger container
Extract the javascript in a dedicated file
Refs #171 
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/simplify_diagram_navigation_example/examples/index.html
> [FEAT] Simplify the 'diagram navigation' example

- examples/custom-behavior/javascript-tooltip-and-popover/index.html
- examples/custom-behavior/javascript-tooltip-and-popover/index.js
Use lib from jsdelivr (previously from unpkg) and bump
- popperjs from 2.5.4 to 2.9.2
- tippy.js from 6.2.7 to 6.3.1
Also use the bpmn-visualization API to set css classes on bpmn elements. This
ensures they are always applied if we activate diagram navigation.
Remove non relevant comments and commented code.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/chore/bump_3rd_party_lib_in_popover_example/examples/index.html
> [INFRA] Bump 3rd party libs in the popup/popover custom behavior example

- demo/monitoring-all-process-instances/execution-data.js
- demo/monitoring-all-process-instances/index.html
- demo/monitoring-all-process-instances/index.js
Add a short text in the page to explain what the example shows.
fix: don't reload the frequency diagram on every toggle
fix: display links to source code
Reduce execution time displayed in edge overlays - only use seconds. This
simulates the latency of the bpmn engine (time taken to process subsequent
element of the process instance) which should be close to 0.
covers https://github.com/process-analytics/bpmn-visualization-js/issues/1174
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/improve_demo_process-monitoring/examples/index.html
> [FEAT] Improve the 'monitoring' demo

- examples/overlays/add-stylized/index.html
- examples/overlays/add-stylized/index.js
- examples/static/css/main.css
Use explicit text in the button that apply the overlays configuration to the
diagram.
js code: use const instead of var
covers https://github.com/process-analytics/bpmn-visualization-js/issues/1174
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/improve_overlays_style_example/examples/index.html
_Previous design_
_New design (initial proposal)_
> [FEAT] Improve settings design in the 'styled overlays' example

- examples/custom-behavior/apply-css-classes/index.html
Add a checkbox to highlight the path step by step, from start to end in addition
to the existing way (all edges, all shapes, both).
This has been used to include the animation in the lib user documentation, see https://github.com/process-analytics/bpmn-visualization-js/pull/1330
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/improve_apply-css-classes_example/examples/index.html
> [FEAT] Improve the 'highlight path' example

- demo/monitoring-all-process-instances/execution-data.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/fix_demo_monitoring/examples/index.html
The darker colors correspond to the higher numbers, and the lighter colors to the smaller numbers.
> [FIX] Fix overlay fill color in the Frequency monitoring demo

- examples/custom-bpmn-theme/custom-user-task-icon/custom-user-task-icon.js
Don't use object destructuring to simplify syntax. We have done this in the lib, we missed
to do it in the example.
covers https://github.com/process-analytics/bpmn-visualization-js/issues/542
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/e755ceba1fbb2aab6df1682ebe23371d7f227cb3/examples/index.html
**Resources**
- Related change in bpm-visualization: https://github.com/process-analytics/bpmn-visualization-js/pull/1002
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
> [REFACTOR] Simplify custom user task icon code

- examples/misc/compare-with-bpmn-js/index.html
Note: as in #190, I tried to bump `kie-editors` but the 0.11.0 fails at initialization and BPMN load time.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/infra/bump_bpmn-js_competitor_lib_version/examples/index.html
> [FEAT] Bump bpmn-js from 8.6.0 to 8.7.1 used in the comparison example

- examples/diagram-navigation/diagram-navigation/README.md
- examples/diagram-navigation/diagram-navigation/index.html
- examples/diagram-navigation/diagram-navigation/index.js
The example now let choose panning without or with scrollbars.
closes #23 
closes https://github.com/process-analytics/bpmn-visualization-js/issues/735
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/23-navigate_with_scrollbars/examples/index.html
> [FEAT] Update navigation example - let use scrollbars for panning

- demo/monitoring-all-process-instances/js/execution-data/time-execution-data.js
Avoid usage of green and red which are dedicated to signal OK/KO states.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/monitoring_demo/change_legend_colors_for_time_data/examples/index.html
Before
Covers #204
> [FEAT] Monitoring demo: Change legend colors for time data

- demo/hacktoberfest-custom-themes/index.html
- demo/hacktoberfest-custom-themes/js/theme-bpmn-visualization.js
- examples/custom-bpmn-theme/custom-colors/README.md
- examples/custom-bpmn-theme/custom-colors/index.html
- examples/custom-bpmn-theme/custom-colors/index.js
- examples/custom-bpmn-theme/custom-fonts/README.md
- examples/custom-bpmn-theme/custom-fonts/index.html
- examples/custom-bpmn-theme/custom-fonts/index.js
- examples/static/js/style-identifiers.js
The bpmn-visualization IIFE bundle will not export mxConstants in the future
as it is not part of our code. This had been done temporarily to keep examples
working.
The examples now use helper classes to access to the style string identifiers in
replacement of mxConstants.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/refactor/remove_usage_of_mxgraph_mxconstants/examples/index.html
> [REFACTOR] Remove usage of mxgraph.mxConstants in examples

- README.md
The paragraph was previously in the examples section whereas it also and mainly applies
to the demo from the bpmn-visualization lib.
> [DOC] Improve 'how to run locally' in README

- examples/index.html
- examples/misc/compare-with-kie-editors-standalone/README.md
- examples/misc/compare-with-kie-editors-standalone/index.html
- examples/misc/compare-with-kie-editors-standalone/index.js
Bump from 0.9.0 to 0.13.0.
Also configure the `onError` hook and manage `setContent` returned promise to
better demonstrate the API usage.
closes #217
closes #218
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/45de4151/examples/misc/compare-with-kie-editors-standalone/index.html
> [FEAT] Bump kie-editors-standalone in the comparison example

- demo/predictions/css/demo.css
- demo/predictions/index.html
- demo/predictions/js/bpmn-diagram-bpmn-spec-pizza.js
- demo/predictions/js/index.js
- demo/predictions/js/prediction-use-case.js
Style the paths for the 2 use cases. We use very specific css selectors (at
least more precise than in already existing examples and demo).
It is also applied to the label but is only visible after zooming or panning
because of a bug in `bpmn-visualization`.
Improve the layout of the pizza diagram:
- remove message flow icon: it is currently not possible to style for now with `bpmn-visualization@0.20.0`: https://github.com/process-analytics/bpmn-visualization-js/issues/1622)
- align elements in pool to have vertical message flow (improve clarity)
closes #263 
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/263-style_executed_paths/demo/predictions/index.html
**Path styling for the 'predicted late' use case**
Same behaviour with …
> [FEAT] 'Predictions' demo: reduce visibility of already executed paths

- demo/predictions/css/demo.css
- demo/predictions/js/prediction-use-case.js
covers #261
Add a blur effect on hover for elements that will be actionable. A popover will
be available on click.
Add a 'pulse' effect on the 'predicated late' element. This signals that actions
are required.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/261_predictions_demo_highlight_running_elements/demo/predictions/index.html
I chose an arbitrary set of colors that could be changed. I suggest we don't do it now and we wait for now. It will be easier to update all colors when all elements of the demo will be integrated. Otherwise, I am afraid that we will change the colors in each PR.
hover on running task: exhibit bug in `bpmn-visualization` https://github.com/process-analytics/bpmn-visualization-js/issues/920
> [FEAT] 'Predictions' demo: style elements that are in progress 

- demo/predictions/js/bpmn-diagram-bpmn-spec-pizza.js
Limit blank on top
Remove extra lane on bottom
Reduce space between pools
Improve pool and lane width to avoid line overlapping
covers #261
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/261-improve_pizza_diagram/demo/predictions/index.html
**Screenshots done with bpmn-visualization@0.20.0**
before | after
------- | -------
> [FEAT] 'Predictions' demo: improve the 'pizza diagram'

- README.md
Do not put a specific value for the 'year to' part of the license message. This will ease maintenance.
> [DOC] Update license year in README

- demo/predictions/css/demo.css
- demo/predictions/index.html
- demo/predictions/js/bpmn-diagram-bpmn-spec-pizza.js
- demo/predictions/js/prediction-use-case.js
- demo/static/js/use-case.js
Highlight predicted path on hover on predicted late or on-time task.
The style of running elements is toggled when displaying the predicted path to avoid displaying too much information.
  - reduce fit margin to enlarge the diagram
  - diagram: increase 'pizza received' label width for no-wrap on highlight
  - simplify definition of the pulse-animation
  - simplify styles by using the generic BPMN CSS classes introduced in v0.21.0
  - allow passing load options to parent UseCase
  - allow registering style/interactions after diagram load
covers #260
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/261-hightlight_predicted_paths/demo/predictions/index.html
> [FEAT] 'Predictions' demo: highlight predicted paths

- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-kie-editors-standalone/index.html
bpmn-js from 8.7.1 to 8.9.0
kie-editors-standalone from 0.13.0 to 0.15.0
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/bump_bpmn-vendors_libs/examples/index.html
> [FEAT] Bump version of other BPMN vendor libs

- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-bpmn-js/index.js
- examples/misc/compare-with-bpmn-js/shared.js
- examples/misc/compare-with-kie-editors-standalone/index.html
- examples/misc/compare-with-kie-editors-standalone/index.js
Introduce shared classes for library and UI management + a 'state' shared object.
Examples extend them which reduces duplications a lot.
The shared classes allow a clearer separation between the libs management and actions on the UI.
Errors are better handled: for instance, the 'Last loaded file' info is no longer updated on load failure.
kie-editors-standalone example: manage the 'Fit View' button title and text based on the 'fitView' state for a better feedback for the user.
closes #127 
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/127-remove_duplications_in_bpmn-vendors_comparison_examples/examples/index.html
> [REFACTOR] Remove duplications in comparison with other BPMN vendors

- examples/misc/compare-with-bpmn-js/shared.js
For kie-editors-standalone, this is already managed by the lib itself.
Covers #281
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/281-manage_load_error_in_bpmn-vendors_comparison_examples/examples/index.html
> [FEAT] Display an alert on load error in bpmn-js

- examples/misc/compare-with-bpmn-js/shared.js
- examples/misc/compare-with-kie-editors-standalone/index.js
It is now visible in the Diagram Explorer and Properties panels.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/display_file_name_in_kie_editor_panels/examples/index.html
> [FEAT] Display the file name in the KIE editor panels

- .github/workflows/check-typescript-projects.yml
- examples/projects/typescript-vanilla-with-vitejs/package.json
- examples/projects/typescript-vanilla-with-vitejs/tsconfig.json
Add typed-mxgraph as devDependencies and explain an alternative way without this dependency.
covers https://github.com/process-analytics/bpmn-visualization-js/issues/1808
relates to https://github.com/process-analytics/bpmn-visualization-js/pull/1814: the current PR has been used to test the types provided by the bpmn-visualization PR
> [FEAT] Improve types support in the ViteJS TS project

- README.md
Add a dedicated paragraph about how to reuse the examples content in projects with a special note for TypeScript.
Based on feedback from #294
> [DOC] Improve README about usage in projects

- examples/custom-bpmn-theme/custom-colors/README.md
- examples/custom-bpmn-theme/custom-fonts/README.md
- examples/static/js/style-identifiers.js
We don't provide a way to get the mxGraph `mxConstants` but we documented it in some README files.
So instead, we now explain where the style keys and values can be found in the mxGraph documentation and how to use them in the `bpmn-visualization` context.
This work was started with #243, there were still some references to mxConstants in README
See also feedback in https://github.com/process-analytics/bpmn-visualization-examples/issues/294#issuecomment-1047258908
> [DOC] Remove reference to mxConstants in README files

- examples/custom-behavior/growing-sequence-flow/index.html
- examples/custom-behavior/running-dashed-message-flow/index.html
Use the same text as in the page.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/fix/custom_behaviour_title_of_pages/examples/index.html
> [FIX] Fix the page title of 2 custom behavior examples

- demo/hacktoberfest-custom-themes/index.html
- demo/monitoring-all-process-instances/index.html
- examples/custom-behavior/apply-css-classes/index.html
- examples/custom-behavior/call-activity-with-modal-on-mouse-over/index.html
- examples/custom-behavior/call-activity-with-reload-on-dblclick/index.html
- examples/custom-behavior/call-activity-with-tabs-on-click/index.html
- examples/custom-behavior/growing-sequence-flow/index.html
- examples/custom-behavior/javascript-tooltip-and-popover/index.html
- examples/custom-behavior/popover-static/index.html
- examples/custom-behavior/running-dashed-message-flow/index.html
- examples/custom-behavior/select-elements-by-bpmn-kind/index.html
- examples/custom-bpmn-theme/custom-colors/index.html
- examples/custom-bpmn-theme/custom-fonts/index.html
- examples/custom-bpmn-theme/custom-user-task-icon/index.html
- examples/diagram-navigation/diagram-fit-after-load/index.html
- examples/diagram-navigation/diagram-fit-on-load/index.html
- examples/diagram-navigation/diagram-navigation/index.html
- examples/display-bpmn-diagram/01-getting-started/index.html
- examples/display-bpmn-diagram/01-getting-started/index.js
- examples/display-bpmn-diagram/load-local-bpmn-diagrams/index.html
- examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.html
- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-kie-editors-standalone/index.html
- examples/overlays/add-remove/index.html
- examples/overlays/add-stylized/index.html
- examples/overlays/custom-overlay-default-style/index.html
- examples/projects/typescript-vanilla-with-rollup/src/index.html
- examples/projects/typescript-vanilla-with-vitejs/index.html
closes #267
Tasks
- examples
- getting started: I introduced an index.js script because defer has no effect on inline script, see https://developer.mozilla.org/en-US/docs/web/html/element/script#attr-defer
- projects
- webpack: nothing to do, script is injected by webpack
**For testers**
I tested locally.
We need to ensure everything works fine with statically.io
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/267-load_js_file_with_defer/examples/index.html
>  [REFACTOR] Load scripts using the defer attribute

- examples/custom-behavior/select-elements-by-bpmn-kind/index.html
- examples/custom-behavior/select-elements-by-bpmn-kind/index.js
The upcoming bpmn-visualization version changes the edge rendering. There is no more usage of the Segment Connector.
This setting was recomputing the whole edge path. It was able to set the terminal waypoints to the collapsed pools when
the edge was targeting a inner element of the pool (hidden when the pool is collapsed).
There is no more waypoints' computation with the new implementation: in this case, we see a dangling edge. The edge
terminal waypoint are inside the pool.
See #306 and https://github.com/process-analytics/bpmn-visualization-js/pull/1863#issuecomment-1070819537
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/disable_pools_collapsing/examples/index.html
> [FEAT] Disable pool collapsing

- examples/static/js/diagram/bpmn-diagrams.js
Some edge terminals were inside or outside the shape. This was visible with bpmn-visualization@0.23.0.
They are now correctly set to always be on the perimeter of the shapes.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/improve_hacktoberfest_diagram/examples/index.html
> [FEAT] Improve terminal waypoints of the Hacktoberfest diagram

- examples/misc/compare-with-kie-editors-standalone/index.html
I haven't noticed changes about console errors: there are still a lot!
closes #304
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/bump_kie_to_0.18.0/examples/index.html
> [FEAT] Bump kie-editors-standalone from 0.16.0 to 0.18.0 in the misc example

- .github/workflows/update_bpmn_visualization_version.yml
Apply changes recently tested in the playground repository.
The major change is the usage of `GH_RELEASE_TOKEN` instead of `GITHUB_TOKEN` with the dawidd6/action-download-artifact.
According to the action documentation, this lets the action access to artifacts stored in another repository. As we know
this is working with more restricted `GITHUB_TOKEN` permissions in the playground repository, let's apply the change now
instead of waiting for an issue when the permissions restriction will be in place in the `examples` repository.
- https://github.com/dawidd6/action-download-artifact
- https://github.com/process-analytics/github-actions-playground/pull/65
> [INFRA] Improve the bpmn-visualization update workflow

- examples/projects/typescript-vanilla-with-vitejs/src/main.ts
- examples/projects/typescript-vanilla-with-vitejs/src/mxgraph-intializer.ts
No need to configure mxGraph globals as they are already configured by bpmn-visualization.
> [REFACTOR] Simplify mxGraph initialization in vite TS project

- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-kie-editors-standalone/index.html
bpmn-js from 8.9.0 to 9.0.3
kie-editors-standalone from 0.18.0 to 0.19.0
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/bump_bpmn_vendors_lib/examples/index.html
> [FEAT] Bump BPMN vendor libs used in the misc examples

- projects/javascript-vanilla-with-webpack/package.json
- projects/typescript-vanilla-with-rollup/package.json
- projects/typescript-vanilla-with-vitejs/package.json
Use the latest development dependencies
Only allow using more recent patch versions to ensure better compatibility.
> [INFRA] Bump dependencies in integration projects

- projects/typescript-vanilla-with-rollup/package.json
- projects/typescript-vanilla-with-rollup/rollup.config.js
The plugin was relocated from `rollup-plugin-commonjs` to `@rollup/plugin-commonjs` almost 3 years ago.
> [INFRA] dev - Bump @rollup/plugin-commonjs from 10.1.0 to 22.0.0

- scripts/update-lib-version.bash
There is no js file to update in the 'demo' folder. The previous implementation failed because it required a js file to
be present in the folder. it is no longer necessary.
The former error was `sed: can't read **/*.js: No such file or directory`.
> [INFRA] Fix the script that update the lib version

- projects/typescript-vanilla-with-vitejs/README.md
- projects/typescript-vanilla-with-vitejs/package.json
typescript from 4.6.4 to 4.7.4
vite from 2.9.9 to 3.0.0-beta.6
> [INFRA] Bump devDependencies in the "Vitejs" project

- demo/hacktoberfest-custom-themes/index.html
- demo/monitoring-all-process-instances/index.html
- demo/predictions/index.html
- demo/static/css/style.css
- demo/static/js/use-case.js
based on #297
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/bpmn-visualization_version_in_footer_of_demos/examples/index.html
The unreleased "predictions" demo has also been updated.
demo | before | now
---- | ---- | ---- 
hacktoberfest | ![image](https://user-images.githubusercontent.com/27200110/177763601-fd2620e1-4817-499f-bb89-bf4ddc236857.png) | ![image](https://user-images.githubusercontent.com/27200110/177763982-72651779-6736-48c1-b48b-4bd1cea8d0bf.png) |
monitoring | ![image](https://user-images.githubusercontent.com/27200110/177764126-331059b6-c161-4d5f-ae86-e618b086a28f.png) | ![image](https://user-images.githubusercontent.com/27200110/177763737-bbf2b664-22d1-48f6-a4ff-262b4f0743b2.png) |
> [FEAT] Display the lib version in the html page footer (demos)

- examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.js
C.8.0 and C.8.1 files have been available since April 2022 (https://github.com/bpmn-miwg/bpmn-miwg-test-suite/commit/3f6b99df1c3de4915aca7454daa0a0df5fd4060a) but were missing in the example.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/load_more_miwg-test-suite_bpmn_files/examples/index.html
> [FEAT] Allow remote loading of the new miwg-test-suite BPMN files

- examples/static/js/style-identifiers.js
Apply it to `mxConstants` substitutes.
Rationale: see https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-static-only-class.md
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/refactor/use_object_literal_instead_of_static_only_class/examples/index.html
> [REFACTOR] Use object literal instead of static only class

- projects/javascript-vanilla-with-webpack/.npmrc
- projects/javascript-vanilla-with-webpack/package.json
- projects/typescript-vanilla-with-parcel/.npmrc
- projects/typescript-vanilla-with-rollup/.npmrc
- projects/typescript-vanilla-with-rollup/package.json
- projects/typescript-vanilla-with-vitejs/.npmrc
- projects/typescript-vanilla-with-vitejs/package.json
Apply to all projects except Parcel TS as dependencies were already up-to-date.
In addition, configure npm to not generate package-lock. We don't commit lock files because we don't want to have to
update it when bumping the bpmn-visualization version. So it is not used for CI tasks. It was previously only generated
locally and generally not used by developers.
**Notes**
I have tested all dev and build commands locally.
> [INFRA] Update devDependencies in projects

- .github/release.yml
- remove `infra:build` and `infra:repo` that are replaced by `chore`
- add `skip-changelog` to explicitly ignore a Pull Request
> [INFRA] Update release notes generation after label change

- projects/typescript-vanilla-with-parcel/package.json
- projects/typescript-vanilla-with-rollup/package.json
- projects/typescript-vanilla-with-rollup/tsconfig.json
- projects/typescript-vanilla-with-vitejs/package.json
Downgrade to TS 4.5 which is the lowest version that bpmn-visualization needs to work.
Ensure that the TS type checks run in the Rollup project.
Also bump Vite from 3.0.5 to 3.1.1
refs https://github.com/process-analytics/bpmn-visualization-js/issues/2246
> [FEAT] Use the lowest possible version of TypeScript in projects

- demo/hacktoberfest-custom-themes/index.html
- demo/hacktoberfest-custom-themes/js/theme-bpmn-visualization.js
- demo/hacktoberfest-custom-themes/js/theme.js
- demo/hacktoberfest-custom-themes/js/use-case/theme-use-case.js
- examples/static/js/diagram/bpmn-diagrams.js
- examples/static/js/style-identifiers.js
For the 1st time, use a dedicated font to better match the brand guidelines.
Improve the label bounds in the BPMN diagram, especially for the Hacktoberfest 2022 theme. Use the right wording for the lib name: "BPMN Visualization" --> "bpmn-visualization"
General improvements in theme management
- let configure the default font size
- remove duplication when applying the mxgraph styles and better manage default values
- improve the page styles
- display nothing prior the page is fully loaded. Previously several titles were displayed while loading.
- do not duplicate styles and use CSS class instead of inline styles
covers #374
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/d5326c1/demo/hacktoberfest-custom-themes/index.html
dark | …
> [FEAT] Add the new "2022" theme in the Hacktoberfest demo

- projects/javascript-vanilla-with-webpack/README.md
- projects/typescript-vanilla-with-parcel/README.md
Add a link to the documentation of previous versions to guide user that cannot use the latest bpmn-visualization version.
> [DOC] Explain webpack/parcel config for old versions

- tutorials/getting-started/index.html
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/remove_unnecessary_script_from_new_tuto/examples/index.html
> [BUG] Remove unnecessary scripts from `html` page of `getting-started` tutorial

- demo/icpm-2022/index.html
The previous title was "Getting started", probably because the page was created from this tutorial.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/fix/icpm_demo_title/examples/index.html
> [FIX] Update the page title of the ICPM 2022 Demo

- README.md
Hacktoberfest is finished, so use the regular image.
The Hacktoberfest image in the README was introduced in #407
> [DOC] Revert Hacktoberfest hero image from the README

- projects/typescript-angular/package.json
- projects/typescript-angular/src/app/app.module.ts
- projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.css
- projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.html
- projects/typescript-angular/src/app/bpmn-examples/bpmn-examples.component.ts
- projects/typescript-angular/src/app/bpmn-examples/notification-zone.component.ts
- projects/typescript-angular/src/app/bpmn-visualization/bpmn-visualization.component.ts
- projects/typescript-angular/src/app/services/actions-notifier.service.spec.ts
- projects/typescript-angular/src/app/services/actions-notifier.service.ts
- projects/typescript-angular/src/app/services/bpmn-diagram.service.ts
- projects/typescript-angular/src/app/services/bpmn-navigation.service.spec.ts
- projects/typescript-angular/src/app/services/bpmn-navigation.service.ts
- projects/typescript-angular/src/app/utils/types.ts
- projects/typescript-angular/src/styles.css
Add a 'reset zoom level' button that uses the last selected Fit options.
The notifications zone track all actions
- simulated fetch diagram
- load diagram
- reset zoom level (fit)
Also bump all dependencies.
covers #409 
https://user-images.githubusercontent.com/27200110/199914993-a1792b99-198d-41b8-90f9-f098022c8764.mp4
> [FEAT] Angular example: add zoom reset and notifications

- projects/typescript-vanilla-with-parcel/package.json
Add an explicit dependency to `@parcel/core` to use a fixed version. This allows to not rely on parcel peerDependencies declaration which uses minor auto update. The update to the new version always create errors because of parcel components using incompatible versions:
`@parcel/workers: Expected constructor 2.7.0:BundleGraph to be registered with serializer to deserialize`
closes #366
0b88bdbd0d9f928f5927d806fd919cab4084166a uses parcel 2.7.0 whereas a new 2.8.0 version has been released. Unlike #425 that wasn't using a specific version of `@parcel/core`, there is no build issue.
The parcel dependencies are all synchronized (they depend on fixed version of parcel components) but they declare peerDependencies to @parcel/core like in the following extract of the package-lock.json file (I …
> [FIX] Avoid build errors on new parcel releases

- demo/monitoring-all-process-instances/js/execution-data/execution-data.js
- demo/monitoring-all-process-instances/js/execution-data/frequency-execution-data.js
The stroke color should be the same as the fill color to demonstrate a non default stroke color (as already done in the time use case).
It had been put in black by mistake during a refactoring released with version 0.19.2. The stroke now always has the right color.
Also update the JSDoc (parameter types) of functions involved in the fix.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/fix/monitoring_demo_no_black_stroke_overlay_for_frequency_use_case/examples/index.html
before ([0.30.0](https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/v0.30.0/demo/monitoring-all-process-instances/index.html)) | now
---- | ----
PR title already ready to follow #454
Root cause of the issue: unwanted change introduced in …
> fix(monitoring-demo-frequency): update the stroke of the overlays

- .github/dependabot.yml
- .github/pull_request_template.md
- .github/workflows/pr-metadata-checks.yml
- .github/workflows/update_bpmn_visualization_version.yml
Add a dedicated workflow to enforce the rule. It runs on `pull_request_target` to handle PR created by Dependabot and from fork repositories.
Dependabot configuration: change PR title prefix.
Update the GitHub workflows that create commits and PR. They now follow "conventional commits". Update the PR template to document the new syntax for the PR title.
closes #453
For tests, see https://github.com/process-analytics/github-actions-playground/issues/213
> chore: ensure that the PR title follows "Conventional Commits"

- demo/monitoring-all-process-instances/js/index.js
- demo/static/js/use-case.js
Introduce the `useCase` and `dataType` query parameters that let choose the use case (frequency, time) and the data type (both, overlays, paths).
This is useful to bookmark a URL for a specific demonstration or to automate screenshots.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/monitoring_demo_query_param_for_use_case_selection/examples/index.html
- defaults (time and both) - same as before :https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/24966e0/demo/monitoring-all-process-instances/index.html
- frequency and overlays: https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/24966e0/demo/monitoring-all-process-instances/index.html?useCase=frequency&dataType=overlays
- …
> feat(monitoring-demo): select use case with query parameter

- projects/typescript-vanilla-with-rollup/.npmrc
- projects/typescript-vanilla-with-rollup/package.json
- projects/typescript-vanilla-with-rollup/rollup.config.js
- projects/typescript-vanilla-with-rollup/rollup.config.mjs
- projects/typescript-vanilla-with-rollup/src/index.ts
In addition, to the `rollup` library update:
- Bump all dependencies to the latest available version. The typescript lib was kept untouched as we want to keep using an old version.
- Switch from `rollup-plugin-typescript2` to `@rollup/plugin-typescript` to use the plugin provided by the rollup project.
- Introduce the terser plugin to minimize the size of the js assets. This is important especially when the project is deploy for PR preview (#438) or GitHub Pages (#439).
- Update the `package.json` attributes for consistency with other projects and remove unused attributes.
I have locally tested both the build and the development mode (the refresh still works for both TS code, HTML page and assets).
And I also check the PR preview.
The attributes in the `package.json` file has been changed …
> chore(deps): bump to rollup@3 in the Rollup TS project

- demo/draw-path/js/path-use-case.js
- demo/draw-path/js/steps.js
- Make the properties of `PathUseCase` as private
- Move the `state` property and associated functions from `PathUseCase` to `Steps` class.
- Add JSDoc
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/refactor/move_state_from_PathUseCase_to_Steps/examples/index.html
> refactor(demo): move state from `PathUseCase` to `Steps` class on `draw-path` demo

- demo/draw-path/js/style.js
- examples/custom-behavior/apply-css-classes/index.js
This API was introduced in `bpmn-visualization@0.34.0`.
See https://github.com/process-analytics/bpmn-visualization-js/issues/2576
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/bb70581f5ee85826e13cdcd5ac8f5a410875371c/examples/index.html
> refactor: use the new "remove all CSS classes" API

- examples/custom-bpmn-theme/custom-colors/README.md
- examples/custom-bpmn-theme/custom-colors/index.js
- examples/custom-bpmn-theme/custom-fonts/README.md
- examples/custom-bpmn-theme/custom-fonts/index.js
Do not rely on `StyleConfigurator` which is experimental. Use a more stable implementation.
The example previously relied on a private method which was removed in v0.29.2.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/38a6fec/examples/index.html
I considered several implementations for the "default colors" examples that had the issue
- prototype based: adapt the previous implementation. Not readable, complicated, highly thight on a private method of `StyleConfigurator`. 144ca86
- class based: call a "configureStyle" methods after the lib initialization, as we do in other examples. 15e2edf
- StyleDefault. I finally ends with this one as it is simpler to only change the defaults. 38a6fec 
For the "default fonts" example, I only …
> fix: configure custom default fonts and colors

- demo/predictions/index.html
- demo/predictions/js/data.js
- demo/predictions/js/prediction-use-case.js
- demo/predictions/js/style-manager.js
- demo/predictions/js/style.js
[https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/extract_prediction_style/demo/predictions/index.html](https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/extract_prediction_style/demo/predictions/index.html)  
last commit: https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/0f8456c3c834f15c453ea3c07a187dd06498c962/demo/predictions/index.html
Depends on #513
> refactor: extract the styling for the prediction demo in dedicated classes

- examples/custom-bpmn-theme/custom-colors/README.md
- examples/custom-bpmn-theme/custom-colors/index.html
- examples/custom-bpmn-theme/custom-colors/index.js
- examples/custom-bpmn-theme/custom-fonts/README.md
- examples/custom-bpmn-theme/custom-fonts/index.html
- examples/custom-bpmn-theme/custom-fonts/index.js
`StyleDefault` is going to be deprecated mainly because it is a global state. Use mxGraph style instead.
Covers https://github.com/process-analytics/bpmn-visualization-js/issues/1993
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/087f29dee42552ae5a4a1fb21912d50402afd203/examples/index.html
> refactor(theme): use global style instead of StyleDefault

- demo/predictions/js/data.js
- demo/predictions/js/path.js
covers #476
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/fix_compute_path_in_prediction_demo/demo/predictions/index.html
:warning:  This fix don't use anymore the `PathResolver` of **Bonita Day Demo**.
<table><tbody><tr><td>In the <code>master</code> branch</td><td>With this fix</td></tr><tr><td><figure class="image"><img src="https://github.com/process-analytics/bpmn-visualization-examples/assets/4921914/c7655360-b819-4c3e-8872-faa92e69f88b" alt=""></figure></td><td><figure class="image"><img src="https://github.com/process-analytics/bpmn-visualization-examples/assets/4921914/5dfe139e-116e-4c90-b1de-ec611ff0edb3"></figure></td></tr><tr><td><figure class="image"><img src="https://github.com/process-analytics/bpmn-visualization- …
> fix(prediction): fix the computing of the paths in the Prediction demo

- demo/predictions/css/demo.css
- demo/predictions/js/data.js
- demo/predictions/js/path.js
- demo/predictions/js/prediction-use-case.js
- demo/predictions/js/style.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/260-make_non_predicted_path_less_visible/demo/predictions/index.html
Covers #260
> feat(prediction): make non predicted path less visible

- demo/predictions/css/demo.css
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/260-Review_CSS_to_use_`rem`_instead_of_`em`_or_`px`/demo/predictions/index.html
Depends on #522 
Covers #260
> feat(prediction): review css to use `rem` instead of `em` or `px`

- demo/predictions/css/demo.css
- examples/static/js/diagram/bpmn-diagram-bpmn-spec-pizza.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/260-Restore_message_flow_icons_in_the_BPMN_diagram_once/demo/predictions/index.html
Depends on #523
Covers #260
> feat(prediction): restore message flow icons in the BPMN diagram

- projects/typescript-vue/package.json
- projects/typescript-vue/src/app.vue
- projects/typescript-vue/src/bpmn-utils.ts
Use the new `ShapeUtil.isBpmnArtifact` method instead of the custom implementation stored in the demo.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/6c79e20f05e65d6b64b4aa9f19d6779e12481f5c/examples/index.html
> refactor(vue-demo): use `bv-experimental-add-ons`

- .github/workflows/update_bpmn_visualization_version.yml
- demo/draw-path/index.html
- demo/hacktoberfest-custom-themes/index.html
- demo/monitoring-all-process-instances/index.html
- demo/prediction/index.html
- examples/custom-behavior/apply-css-classes/index.html
- examples/custom-behavior/call-activity-with-modal-on-mouse-over/index.html
- examples/custom-behavior/call-activity-with-reload-on-dblclick/index.html
- examples/custom-behavior/call-activity-with-tabs-on-click/index.html
- examples/custom-behavior/growing-sequence-flow/index.html
- examples/custom-behavior/javascript-tooltip-and-popover/index.html
- examples/custom-behavior/running-dashed-message-flow/index.html
- examples/custom-behavior/select-elements-by-bpmn-kind/index.html
- examples/custom-bpmn-theme/custom-colors/index.html
- examples/custom-bpmn-theme/custom-edge-marker-colors/index.html
- examples/custom-bpmn-theme/custom-fonts/index.html
- examples/custom-bpmn-theme/custom-user-task-icon/index.html
- examples/diagram-navigation/diagram-fit-after-load/index.html
- examples/diagram-navigation/diagram-fit-on-load/index.html
- examples/diagram-navigation/diagram-navigation/index.html
- examples/display-bpmn-diagram/load-local-bpmn-diagrams/index.html
- examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.html
- examples/display-bpmn-diagram/pools-filter-on-load/index.html
- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-kie-editors-standalone/index.html
- examples/overlays/add-remove/index.html
- examples/overlays/add-stylized/index.html
- examples/overlays/custom-overlay-default-style/index.html
- scripts/update-lib-version.bash
Previously, we load the `bpmn-visualization` IIFE bundle from the `jsdelivr` CDN without integrity. This was not consistent with the rest of resources that we load from this CDN and this could lead to safety risks.
The version of `bpmn-visualization` is updated automatically when a new release is available. Changing the version is easy, but the integrity computation requires more work. As a first implementation, we decided to not do it.
Now, the integrity string is first computed from the bundle of the npm package (the package is downloaded by the GitHub workflow). Then, all pages using the bundle from the jsdelivr CDN are updated with the new version (as before) and with the new integrity string.
All pages have been updated to use the `bpmn-visualization` 0.39.0 integrity value in order …
> feat: use resource integrity when loading bpmn-visualization from CDN

- demo/draw-path/index.html
- demo/monitoring-all-process-instances/index.html
This applies to the `variancecharts`.
Also stop loading it in the draw-path demo as it is not used there.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/feat/resource_integrity_external_lib/examples/index.html
- https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity: provide details and how-to generate integrity string
> feat: check integrity of all external JS loaded from CDN

- examples/misc/compare-with-bpmn-js/index.html
- examples/misc/compare-with-kie-editors-standalone/index.html
- bpmn-js: 13.0.4 to 14.0.0
- kie-editors-standalone: 0.28.0 to 0.31.0
closes #539
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/9513bef/examples/index.html
> chore: bump version of competitors in examples

- examples/custom-behavior/javascript-tooltip-and-popover/index.html
- examples/custom-behavior/select-elements-by-bpmn-kind/index.html
Updated resources
- notyf from 3.9.0 to 3.10.0
- popper.js from 2.9.2 to 2.11.8
- tippy.js from 6.3.1 (development) to 6.3.7 (production minified)
closes #271
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/1d13196/examples/index.html
```[tasklist]
```
> chore: update 3rd party libs used in examples

- projects/typescript-vanilla-with-parcel/package.json
- I tested the dev server locally
- parcel changelog: https://github.com/parcel-bundler/parcel/releases/tag/v2.10.0
> chore(dev-deps): bump parcel from 2.9.3 to 2.10.0

- examples/custom-behavior/javascript-tooltip-and-popover/index.js
Except for the "name" property (found in the header), only valued properties are displayed, so that only data of interest is shown.
closes #549
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/fix/549-hide_undefined_properties_of_BpmnSemantic/examples/custom-behavior/javascript-tooltip-and-popover/index.html
> fix(BpmnSemantic): do not display properties with undefined values

- demo/hacktoberfest-custom-themes/index.html
- demo/hacktoberfest-custom-themes/js/index.js
- demo/hacktoberfest-custom-themes/js/theme-bpmn-visualization.js
- demo/hacktoberfest-custom-themes/js/use-case/hacktoberfest-use-case.js
- demo/hacktoberfest-custom-themes/js/use-case/theme-use-case.js
- demo/monitoring-all-process-instances/index.html
- demo/monitoring-all-process-instances/js/index.js
- demo/monitoring-all-process-instances/js/monitoring-use-case.js
- demo/prediction/index.html
- demo/prediction/js/index.js
- demo/prediction/js/prediction-use-case.js
- demo/static/js/use-case.js
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/refactor/use_cases_in_demos/examples/index.html
> refactor(demo): simplify the UseCase classes and how to set theme

- projects/typescript-vanilla-with-rollup/package.json
Also use a version of `@types/node` that is compatible with TypeScript 4.5.
> chore(dev-deps): bump rollup dependencies

- examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.js
The files were recently added to the miwg-test-suite repository.
https://cdn.statically.io/gh/process-analytics/bpmn-visualization-examples/54ae2e23f6959d6e64f58f10bb4923707994d8e7/examples/display-bpmn-diagram/load-remote-bpmn-diagrams/index.html
C.9.0 | C.9.1 | C.9.2
---- | ---- | ----
> feat: add new miwg reference diagrams in the "load remote" example

- projects/javascript-vanilla-with-webpack/package.json
- projects/typescript-lit-element/package.json
- projects/typescript-vanilla-with-parcel/package.json
- projects/typescript-vanilla-with-rollup/package.json
- projects/typescript-vanilla-with-rsbuild/package.json
- projects/typescript-vanilla-with-vitejs/package.json
- projects/typescript-vue/package.json
This includes:
- bump lit from 2.7.5 to 3.3.0
@lit/reactive-element uses types introduced in TS 5.0. So bump typescript from 4.1.6 to 5.8.3.
- parcel from 2.12.0 to 2.14.4
- rollup from 4.24.0 to 4.40.0 (also bump plugins)
- rsbuild from 1.0.5 to 1.3.7
- vite from 5.4.7 to 6.3.0
- vue from 3.5.6 to 3.5.13 (and plugins)
Switch to ESM to remove a vite warning
- webpack from 5.94.0 to 5.99.5
Evolution of the bundle size, this is to measure the impact of the bump of fast-xml-parser in bpmn-visualization in https://github.com/process-analytics/bpmn-visualization-js/pull/3327#pullrequestreview-2773102076
example | 0.46.0 | dev [5aa8091](https://github.com/process-analytics/bpmn-visualization-js/tree/5aa8091daf0459afda7fd0bc13a42ab0b76291fc)
---- | ---- | ----
rollup | 992.6 kB | 993.4 kB …
> chore(deps-dev): bump dependencies in projects

- projects/typescript-vue/package.json
Also bump typescript from 5.2.2 to 5.4: the new vue version uses the `NoInfer` utility type introduced in TS 5.4.
> chore(deps-dev): bump vue from 3.5.13 to 3.5.20
